### ISSUE TITLE
`MetaDataset::calculateTrainingData()` overwrites meta-target

### ISSUE THREAD

**Issue by Jakob-Bach** [CemOezcan/metalfi#23]
If combining multiple base datasets into one `MetaDataset`, the function `MetaDataset::calculateTrainingData()` appends the meta-datasets (without meta-targets) to a list, but the meta-targets are stored in a plain (non-list) variable `targets`, which is newly assigned in each iteration. However, each of the meta-datasets should have its own meta-targets.

Currently this should have no consequences, because `controller.py` creates a separate `MetaDataset` object for each base dataset anyway, so the loop just goes over one element.

**Comment by CemOezcan** [comment]
The variable `targets` in `MetaDataset::calculateTrainingData()` is a list that contains the names of all meta-targets (which are the same for every meta-dataset). See `MetaFeatures::addTarget()`. 

Originally, I intended to store only one file containing all the meta-data, which is why the loop in `MetaDataset::calculateTrainingData()` exists, but is not used.

**Comment by Jakob-Bach** [comment]
Okay, then it probably should just be refactored to be less confusing, I didn't go though the method chain to see what is returned, I just looked at the name.
